version: '3'
services:
  pgsql:
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - 5432:5432
    container_name: pgsql
    networks:
      - skynet
  popcorn:
    build:
      context: .
    image: popcorn
    environment:
      DATABASE_URL: ${DATABASE_URL}
    container_name: popcorn
    ports:
      - 3000:3000
    networks:
      - skynet
networks:
  skynet:
    driver: bridge
