version: '3'
services:
  pgsql:
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
    ports:
      - 5432:5432
    container_name: 'pgsql'
    networks:
      - skynet
networks:
  skynet:
    driver: bridge